[paths]
app = "/path/to/repo"
data = "/path/to/data"
rag_data = "/path/to/ragdata"
rag_cache = "/path/to/ragdata.db"

[model]
name = "microsoft/Phi-3-mini-4k-instruct"
output_name = "genraitor"
embed_name = "ollama"
api_key = ""

[training]
attention = "flash_attention_2" # or "eager"
